# sonarr-test.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv
  labels:
    app: sonarr
  namespace: sonarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
  labels:
    app: sonarr
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - image: linuxserver/sonarr
          imagePullPolicy: Always
          name: sonarr
          volumeMounts:
            - mountPath: /sonarr
              name: sonarr-data
      volumes:
        - name: sonarr-data
          persistentVolumeClaim:
            claimName: sonarr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  type: LoadBalancer
  ports:
    - name: web-interface
      port: 8989
  selector:
    app: sonarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: sonarr
spec:
  rules:
    - host: sonarr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
