apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
    - cidr: "10.0.10.0/24"
  serviceSelector:
    matchExpressions:
      - key: color
        operator: In
        values:
          - blue
          - cyan
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "red-pool"
spec:
  blocks:
    - cidr: "10.0.10.0/24"
  serviceSelector:
    matchExpressions:
      - key: color
        operator: In
        values:
          - red
