# Found here - https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.yaml
# User configured values are all to be listed below.
cluster:
  name: abode
  id: 1
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
k8sServiceHost: 192.168.15.5
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
externalIPs:
  enabled: true
k8sClientRateLimit:
  qps: 50
  burst: 200
operator:
  rollOutPods: true
rollOutCiliumPods: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.15.31
