# Found here - https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.yaml
# User configured values are all to be listed below.
cluster:
  name: abode
  id: 1
bpf:
  masquerade: true
ipam:
  mode: kubernetes
  multiPoolPreAllocation: ""
egressGateway:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
# Ingress Controller
ingressController:
  enabled: true
  loadbalancerMode: dedicated
# L2 Announcement Rate Limiting
k8sClientRateLimit:
  burst: 10
  qps: 5
# Default hosting values
k8sServiceHost: 192.168.15.5
k8sServicePort: 6443
# Disabled kube-proxy
kubeProxyReplacement: true
# L2 Announcement enabled
l2announcements:
  enabled: true
