---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: democratic-csi
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: '0.14.7'
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 1h
      valuesFiles:
        - nfs-base.yml
        - nfs-secrets.yml
  values:
    csiDriver:
      name: "nfs"
    storageClasses:
      - name: nfs
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions:
          - noatime
          - nfsvers=4
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: 'nfs-snapshot'
        parameters:
          detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.15.24
          port: 80
          allowInsecure: true
          apiKey: ${TRUENAS_API_KEY}
        zfs:
          datasetParentName: /k8s/nfs/volumes
          detachedSnapshotsDatasetParentName: /k8s/nfs/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0770"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 192.168.15.24
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
