---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: democratic-csi-system
spec:
  interval: 1m0s
  url: https://democratic-csi.github.io/charts/
