---
# Steps in here can take place across all nodes
- name: Prep update
  ansible.builtin.apt:
    update_cache: true

- name: Add Kubernetes APT repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/"
    signed_by: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
    suites: /
    state: present
    enabled: true

- name: Update Apt cache.
  apt:
    update_cache: true

- name: Now install the pkgs
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl

- name: Hold the installed packages
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
