---
- name: Prep update
  ansible.builtin.apt:
    update_cache: true

- name: Install outlined packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-debian
