---
- name: Base-image Hardening
  hosts: kubernetes
  gather_facts: true
  become: true

  pre_tasks:
    - name: Grab my vault
      ansible.builtin.include_vars:
        file: /home/matt/Repos/ansible-vault/kubernetes.yml

  tasks:

    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ root_passwd | password_hash('sha512')}}"

    - name: Change user password
      ansible.builtin.user:
        name: ftl
        password: "{{ ftl_passwd | password_hash('sha512')}}"
