apiVesion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: '1.17.2'
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 12h
