---
cluster:
  id: 1
  name: abode
externalIPs:
  enabled: true
gatewayAPI:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
ingressController:
  default: true
  enabled: true
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.15.31
k8sClientRateLimit:
  burst: 200
  qps: 50
k8sServiceHost: 192.168.15.5
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
operator:
  rollOutPods: true
rollOutCiliumPods: true
